version: '3.8'

services:
  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - MODEL_NAME=llama3.1-70b